3.1_:3

In [21]:
import sys
import platform

import numpy as np
import pandas as pd

In [22]:
try:
    import sklearn
except Exception as e:
    sklearn = None
    print("⚠️ scikit-learn не импортируется:", e)


In [23]:
print("Python:", sys.version.split()[0])
print("Executable:", sys.executable)
print("OS:", platform.platform())

print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)
if sklearn is not None:
    print("scikit-learn:", sklearn.__version__)

Python: 3.14.3
Executable: C:\Users\ukohn\AppData\Local\Python\pythoncore-3.14-64\python.exe
OS: Windows-11-10.0.26200-SP0
NumPy: 2.4.2
Pandas: 3.0.1
scikit-learn: 1.8.0


In [24]:
np.random.seed(42)

In [25]:
X = np.random.randn(100, 5)

In [26]:
print("Shape:", X.shape)
print("Dtype:", X.dtype)

Shape: (100, 5)
Dtype: float64


In [27]:
print("First 5 rows:")
print(X[:5])

First 5 rows:
[[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337]
 [-0.23413696  1.57921282  0.76743473 -0.46947439  0.54256004]
 [-0.46341769 -0.46572975  0.24196227 -1.91328024 -1.72491783]
 [-0.56228753 -1.01283112  0.31424733 -0.90802408 -1.4123037 ]
 [ 1.46564877 -0.2257763   0.0675282  -1.42474819 -0.54438272]]


3.1_:3

In [28]:
overall_mean = X.mean()
overall_std = X.std()

In [29]:
col_mean = X.mean(axis=0)
col_std = X.std(axis=0)
col_min = X.min(axis=0)
col_max = X.max(axis=0)

In [30]:
print("Overall mean:", overall_mean)
print("Overall std:", overall_std)
print("\nPer-column mean:", col_mean)
print("Per-column std:", col_std)
print("Per-column min:", col_min)
print("Per-column max:", col_max)

Overall mean: 0.006837994588647575
Overall std: 0.9802715029966268

Per-column mean: [-0.04474719  0.07695423 -0.09387351  0.12805847 -0.03220203]
Per-column std: [0.89583921 0.9791772  0.97901142 0.95474576 1.06742857]
Per-column min: [-1.9520878  -2.30192116 -3.24126734 -1.91328024 -2.6197451 ]
Per-column max: [2.31465857 1.8861859  2.1221562  3.07888081 3.85273149]


4.1_:3

In [31]:
w = np.random.randn(5,)

In [32]:
y = X @ w

In [ ]:
print("y.shape:", y.shape)
print("First values:", y[:5])

4.2_:3

In [33]:
w_true = np.array([1.5, -2.0, 0.0, 0.7, 3.0])
noise = 0.1 * np.random.randn(X.shape[0])
y_true = X @ w_true + noise

In [34]:
w_guess = w_true + 0.5 * np.random.randn(5)
y_pred = X @ w_guess

In [35]:
mse = np.mean((y_true - y_pred) ** 2)
mae = np.mean(np.abs(y_true - y_pred))
rmse = np.sqrt(mse)

In [36]:
ss_res = np.sum((y_true - y_pred) ** 2)
ss_tot = np.sum((y_true - y_true.mean()) ** 2)
r2 = 1 - ss_res / ss_tot

In [37]:
print("MSE:", mse)
print("MAE:", mae)
print("RMSE:", rmse)
print("R2:", r2)

MSE: 2.6179517731099695
MAE: 1.2687155830236363
RMSE: 1.6180085825204913
R2: 0.8296792210419167


5.1_:3